/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const ThreadsNewLazyImport = createFileRoute('/threads/new')()
const ThreadsThreadIdIndexLazyImport = createFileRoute('/threads/$threadId/')()

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ThreadsNewLazyRoute = ThreadsNewLazyImport.update({
  path: '/threads/new',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/threads/new.lazy').then((d) => d.Route))

const ThreadsThreadIdIndexLazyRoute = ThreadsThreadIdIndexLazyImport.update({
  path: '/threads/$threadId/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/threads/$threadId/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/threads/new': {
      id: '/threads/new'
      path: '/threads/new'
      fullPath: '/threads/new'
      preLoaderRoute: typeof ThreadsNewLazyImport
      parentRoute: typeof rootRoute
    }
    '/threads/$threadId/': {
      id: '/threads/$threadId/'
      path: '/threads/$threadId'
      fullPath: '/threads/$threadId'
      preLoaderRoute: typeof ThreadsThreadIdIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  ThreadsNewLazyRoute,
  ThreadsThreadIdIndexLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/threads/new",
        "/threads/$threadId/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/threads/new": {
      "filePath": "threads/new.lazy.tsx"
    },
    "/threads/$threadId/": {
      "filePath": "threads/$threadId/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
